### ISSUE TITLE
unable to start java server using latest package version (Ubuntu 20.04 LTS)

### ISSUE THREAD

**Issue by achubaty** [CWFC-CCFB/J4R#12]
Hello, this was working previously (v1.1.8 using j4r_server-1.1.6) but the latest version of J4R (v1.1.9 using j4r_server-1.1.7) no longer works on Ubuntu 20.04 LTS.

## java info

```
$ java --version
openjdk 11.0.18 2023-01-17
OpenJDK Runtime Environment (build 11.0.18+10-post-Ubuntu-0ubuntu120.04.1)
OpenJDK 64-Bit Server VM (build 11.0.18+10-post-Ubuntu-0ubuntu120.04.1, mixed mode, sharing)
```

## v1.1.8

```r
> connectToJava()
Starting local Java server...
Mar. 31, 2023 10:36:29 A.M. j4r.lang.codetranslator.REnvironment main
INFO: ClassPath = /home/achubaty/.local/share/R/LandR_MPB/packages/x86_64-pc-linux-gnu/4.2/J4R/java/j4r_server-1.1.6.jar
Mar. 31, 2023 10:36:29 A.M. j4r.multiprocess.JavaProcess createIndependentProcess
INFO: Starting Java process with command = [/usr/lib/jvm/java-11-openjdk-amd64/bin/java, -Djava.awt.headless=true, --add-opens, java.base/jdk.internal.loader=ALL-UNNAMED, -cp, j4r_server-1.1.6.jar, j4r.lang.codetranslator.REnvironment, -ports, 0:0, -backdoorport, 0:0, -wd, /home/achubaty/Documents/GitHub/LandR_MPB]
[1] TRUE
```

## v1.1.9

```r
> library(J4R)
Welcome to J4R!
Please, make sure that Java (version 8 or later) is installed on your computer.
For more information, visit https://github.com/CWFC-CCFB/J4R/wiki .
> connectToJava()
Starting local Java server...
Mar. 31, 2023 10:42:45 A.M. j4r.lang.codetranslator.REnvironment main
INFO: ClassPath = "j4r_server-1.1.7.jar"
Mar. 31, 2023 10:42:45 A.M. j4r.multiprocess.JavaProcess createIndependentProcess
INFO: Starting Java process with command = [/usr/lib/jvm/java-11-openjdk-amd64/bin/java, -Djava.awt.headless=true, --add-opens, java.base/jdk.internal.loader=ALL-UNNAMED, -cp, "j4r_server-1.1.7.jar", j4r.lang.codetranslator.REnvironment, -ports, 0:0, -backdoorport, 0:0, -wd, /home/achubaty/GitHub/LandR_MPB]
Error in connectToJava() : 
  It seems the local Java server has failed to start!
```

`dmesg` shows segfault(s) when trying to start the java server from R but I can't seem to find any additional logging of errors from the java process.

Looking at the R code, the error message is specifically triggered by not finding the J4R temp file after 8 seconds, and I can confirm that manually running the sysetm command returns status code 0 but no file is produced and I cannot see a java process in `htop`.

**Comment by donenrique24** [comment]
I just reproduced the bug. I am out of the office at the moment. I'll work on that first thing when I get back to the office on Apr 17th. Sorry for the delay. In the meantime, you can roll back to version 1.1.8. 

Just change the URL in 
install.packages("https://sourceforge.net/projects/repiceasource/files/latest/download", repos = NULL,  type="source")

All the releases are available at https://sourceforge.net/projects/repiceasource/files/

**Comment by achubaty** [comment]
thanks - using v1.1.8 for now

**Comment by donenrique24** [comment]
Hi Alex, don't know if you had planned to use the BioSIMclient package as well, but the server is currently down due to the massive power outage we had last week in Quebec. Unfortunately, I have been unable to put the server back online remotely. This will have to wait until I get back to the office on Apr 17th... Sorry for the inconvenience.

**Comment by achubaty** [comment]
Thanks for letting me know.

**Comment by achubaty** [comment]
Awesome, thanks for fixing. I will test later today.
